CREATE TABLE AIRCRAFT 
(
  AIRCRAFT_ID NUMBER NOT NULL 
, MAX_TAKEOFF_WEIGHT NUMBER NOT NULL 
, MAX_LANDING_WEIGHT NUMBER NOT NULL 
, FIRST_CLASS_CAPACITY NUMBER NOT NULL 
, BUSINESS_CLASS_CAPACITY NUMBER NOT NULL 
, ECONOMY_CLASS_CAPACITY NUMBER NOT NULL 
, CONSTRAINT AIRCRAFT_PK PRIMARY KEY 
  (
    AIRCRAFT_ID 
  )
  ENABLE 
);
