CREATE TABLE AIRPORT 
(
  AIRPORT_ID NUMBER NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, CITY VARCHAR2(20) NOT NULL 
, COUNTRY VARCHAR2(20) NOT NULL 
, CONSTRAINT AIRPORT_PK PRIMARY KEY 
  (
    AIRPORT_ID 
  )
  ENABLE 
);
