--Created Tablespace  
CREATE TABLESPACE tbs_perm_01
  DATAFILE 'tbs_perm_01.dat' 
    SIZE 20M
  ONLINE;

--Creating permanent TABLESPACE
CREATE TABLESPACE tbs_perm_02
  DATAFILE 'tbs_perm_02.dat' 
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
	
CREATE TEMPORARY TABLESPACE tbs_temp_01
  TEMPFILE 'tbs_temp_01.dbf'
    SIZE 5M
    AUTOEXTEND ON;
  
alter session set "_ORACLE_SCRIPT"=true;

--Create user
CREATE USER TERMPROJECT
 IDENTIFIED BY awsaf114fuad113
 DEFAULT TABLESPACE tbs_perm_01
 TEMPORARY TABLESPACE tbs_temp_01
 QUOTA 20M on tbs_perm_01;
 
--Grant user access
GRANT create session TO TERMPROJECT;
GRANT create table TO TERMPROJECT;
GRANT create view TO TERMPROJECT;
GRANT create any trigger TO TERMPROJECT;
GRANT create any procedure TO TERMPROJECT;
GRANT create sequence TO TERMPROJECT;
GRANT create synonym TO TERMPROJECT;


CREATE TABLE EMPLOYEE 
(
  EMPLOYEE_ID NUMBER(20) NOT NULL 
, FIRST_NAME VARCHAR2(20) NOT NULL 
, LAST_NAME VARCHAR2(20) NOT NULL 
, GENDER VARCHAR2(20) NOT NULL 
, PHONE_NUMBER VARCHAR2(20) NOT NULL 
, ADDRESS VARCHAR2(20) NOT NULL 
, EMAIL_ID VARCHAR2(20) 
, HIRE_DATE DATE NOT NULL 
, NATIONALITY VARCHAR2(20) NOT NULL 
, SALARY NUMBER NOT NULL 
, DESIGNATION VARCHAR2(20) NOT NULL 
, CONSTRAINT EMPLOYEE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
);

CREATE TABLE AIRPORT 
(
  AIRPORT_ID NUMBER NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, CITY VARCHAR2(20) NOT NULL 
, COUNTRY VARCHAR2(20) NOT NULL 
, CONSTRAINT AIRPORT_PK PRIMARY KEY 
  (
    AIRPORT_ID 
  )
  ENABLE 
);

CREATE TABLE ROUTE 
(
  ROUTE_ID NUMBER NOT NULL 
, SOURCE NUMBER NOT NULL 
, DESTINATION NUMBER NOT NULL 
, CONSTRAINT ROUTE_PK PRIMARY KEY 
  (
    ROUTE_ID 
  )
  ENABLE 
);

CREATE TABLE AIRCRAFT 
(
  AIRCRAFT_ID NUMBER NOT NULL 
, MAX_TAKEOFF_WEIGHT NUMBER NOT NULL 
, MAX_LANDING_WEIGHT NUMBER NOT NULL 
, FIRST_CLASS_CAPACITY NUMBER NOT NULL 
, BUSINESS_CLASS_CAPACITY NUMBER NOT NULL 
, ECONOMY_CLASS_CAPACITY NUMBER NOT NULL 
, CONSTRAINT AIRCRAFT_PK PRIMARY KEY 
  (
    AIRCRAFT_ID 
  )
  ENABLE 
);

CREATE TABLE SCHEDULE 
(
  FLIGHT_ID NUMBER NOT NULL 
, AIRCRAFT_ID NUMBER NOT NULL 
, ROUTE_ID NUMBER NOT NULL 
, ARRIVAL_DATE_TIME TIMESTAMP NOT NULL 
, DEPART_DATE_TIME TIMESTAMP NOT NULL 
, FLIGHT_TYPE VARCHAR2(20) NOT NULL 
, CONSTRAINT SCHEDULE_PK PRIMARY KEY 
  (
    FLIGHT_ID 
  )
  ENABLE 
);

CREATE TABLE AIRCRAFT_INFO 
(
  AIRCRAFT_ID NUMBER NOT NULL 
, PRICE FLOAT NOT NULL 
, LENGTH NUMBER NOT NULL 
, HEIGHT NUMBER NOT NULL 
, WINGSPAN NUMBER NOT NULL 
, CABIN_WIDTH NUMBER NOT NULL 
, CRUISING_SPEED NUMBER NOT NULL 
, START_OF_SERVICE TIMESTAMP NOT NULL 
, END_OF_SERVICE TIMESTAMP NOT NULL 
, TOTAL_FLIGHTS NUMBER NOT NULL 
, CONSTRAINT AIRCRAFT_INFO_PK PRIMARY KEY 
  (
    AIRCRAFT_ID 
  )
  ENABLE 
);

CREATE TABLE PRICE 
(
  PRICE_ID VARCHAR2(20) NOT NULL 
, ROUTE_ID VARCHAR2(20) NOT NULL 
, FIRST_CLASS VARCHAR2(20) NOT NULL 
, BUSINESS_CLASS VARCHAR2(20) NOT NULL 
, ECONOMY_CLASS VARCHAR2(20) NOT NULL 
, CONSTRAINT PRICE_PK PRIMARY KEY 
  (
    PRICE_ID 
  )
  ENABLE 
);

CREATE TABLE BOOKING 
(
  BOOKING_ID NUMBER NOT NULL 
, FLIGHT_ID NUMBER NOT NULL 
, PASSENGER_ID NUMBER NOT NULL 
, CLASS VARCHAR2(20) NOT NULL 
, DATE_TIME TIMESTAMP NOT NULL 
, PAYMENT_STATUS VARCHAR2(20) NOT NULL 
, AMOUNT_PAYABLE FLOAT NOT NULL 
, CONSTRAINT BOOKING_PK PRIMARY KEY 
  (
    BOOKING_ID 
  )
  ENABLE 
);

CREATE TABLE PASSENGER 
(
  PASSENGER_ID NUMBER NOT NULL 
, FIRST_NAME VARCHAR2(20) NOT NULL 
, LAST_NAME VARCHAR2(20) NOT NULL 
, PHONE_NUMBER NUMBER 
, DATE_OF_BIRTH DATE NOT NULL 
, GENDER VARCHAR2(20) NOT NULL 
, PASSPORT_NUMBER VARCHAR2(20) 
, EMAIL_ID VARCHAR2(20) 
, ADDRESS VARCHAR2(20) 
, NATIONALITY VARCHAR2(20) NOT NULL 
, CATEGORY VARCHAR2(20) NOT NULL 
, CONSTRAINT PASSENGER_PK PRIMARY KEY 
  (
    PASSENGER_ID 
  )
  ENABLE 
);

CREATE TABLE BOARDING 
(
  BOARDING_ID NUMBER NOT NULL 
, PASSENGER_ID NUMBER NOT NULL 
, FLIGHT_ID NUMBER NOT NULL 
, BOOKING_ID NUMBER NOT NULL 
, BAGGAGE_NUMBER NUMBER NOT NULL 
, BAGGAGE_WEIGHT FLOAT NOT NULL 
, SEAT_NUMBER VARCHAR2(20) NOT NULL 
, CONSTRAINT BOARDING_PK PRIMARY KEY 
  (
    BOARDING_ID 
  )
  ENABLE 
);

CREATE TABLE ENGINEER 
(
  EMPLOYEE_ID NUMBER NOT NULL 
, DEPARTMENT VARCHAR2(20) NOT NULL 
, CONSTRAINT ENGINEER_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
);

CREATE TABLE MAINTENANCE 
(
  MAINTENANCE_ID NUMBER NOT NULL 
, PLANE_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, DEPARTMENT VARCHAR2(20) NOT NULL 
, OUT_OF_SERVICE DATE NOT NULL 
, BACK_TO_SERVICE DATE NOT NULL 
, CONSTRAINT MAINTENANCE_PK PRIMARY KEY 
  (
    MAINTENANCE_ID 
  )
  ENABLE 
);

CREATE TABLE PARTS 
(
  MAINTENANCE_ID NUMBER NOT NULL 
, PARTS_ID NUMBER NOT NULL 
);

CREATE TABLE PARTS_INFO 
(
  PARTS_ID NUMBER NOT NULL 
, PRICE FLOAT NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, DESCRIPTION VARCHAR2(20) 
, CONSTRAINT PARTS_INFO_PK PRIMARY KEY 
  (
    PARTS_ID 
  )
  ENABLE 
);

CREATE TABLE FUEL 
(
  FUEL_ID NUMBER NOT NULL 
, PLANE_ID NUMBER NOT NULL 
, FLIGHT_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, COST_PER_GALLON FLOAT NOT NULL 
, QUANTITY NUMBER NOT NULL 
, CONSTRAINT FUEL_PK PRIMARY KEY 
  (
    FUEL_ID 
  )
  ENABLE 
);

CREATE TABLE CREW_EXPENSE 
(
  EXPENSE_ID NUMBER NOT NULL 
, CREW_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, COST FLOAT NOT NULL 
, CONSTRAINT CREW_EXPENSE_PK PRIMARY KEY 
  (
    EXPENSE_ID 
  )
  ENABLE 
);

CREATE TABLE FLIGHT_CREW 
(
  FLIGHT_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
);

CREATE TABLE DISCOUNT_RATES 
(
  DISCOUNT_ID VARCHAR2(20) NOT NULL 
, PLATINUM VARCHAR2(20) NOT NULL 
, GOLD VARCHAR2(20) NOT NULL 
, SILVER VARCHAR2(20) NOT NULL 
, BRONZE VARCHAR2(20) NOT NULL 
, OFFER_START VARCHAR2(20) NOT NULL 
, OFFER_END VARCHAR2(20) 
, DESCRIPTION VARCHAR2(20) NOT NULL 
, CONSTRAINT DISCOUNT_RATES_PK PRIMARY KEY 
  (
    DISCOUNT_ID 
  )
  ENABLE 
);

-- ROUTE TABLE
ALTER TABLE ROUTE ADD CONSTRAINT AIRPORT_ID_SRC FOREIGN KEY (SOURCE) REFERENCES AIRPORT(AIRPORT_ID);
ALTER TABLE ROUTE ADD CONSTRAINT AIRPORT_ID_DEST FOREIGN KEY (DESTINATION) REFERENCES AIRPORT(AIRPORT_ID);

-- PRICE TABLE
ALTER TABLE PRICE ADD CONSTRAINT ROUTE_PRICE_FK FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ROUTE_ID);

-- SCHEDULE TABLE
ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_ROUTE_FK FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ROUTE_ID);
ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_PRICE_FK FOREIGN KEY (PRICE_ID) REFERENCES PRICE(PRICE_ID);

-- FUEL TABLE
ALTER TABLE FUEL ADD CONSTRAINT FUEL_PLANE_FK FOREIGN KEY (PLANE_ID) REFERENCES AIRCRAFT(PLANE_ID);
ALTER TABLE FUEL ADD CONSTRAINT FUEL_SCHEDULE_FK FOREIGN KEY (FLIGHT_ID) REFERENCES SCHEDULE(FLIGHT_ID);
ALTER TABLE FUEL ADD CONSTRAINT FUEL_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

-- PARTS TABLE
ALTER TABLE PART ADD CONSTRAINT PART_MAINTENANCE_FK FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE(MAINTENANCE_ID);
ALTER TABLE PART ADD CONSTRAINT PART_PART_INFO_FK FOREIGN KEY (PARTS_ID) REFERENCES PARTS_INFO(PARTS_ID);

-- MAINTENANCE TABLE
ALTER TABLE MAINTENANCE ADD CONSTRAINT PLANE_MAINTENANCE_FK FOREIGN KEY (PLANE_ID) REFERENCES AIRCRAFT(PLANE_ID);
ALTER TABLE MAINTENANCE ADD CONSTRAINT MAINTENANCE_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

-- BOOKING TABLE
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_FLIGHT_FK FOREIGN KEY (FLIGHT_ID) REFERENCES SCHEDULE(FLIGHT_ID);
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_PASSENGERR_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID);

-- BOARDING TABLE
ALTER TABLE BOARDING ADD CONSTRAINT BOARDING_PASSENGER_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID);
ALTER TABLE BOARDING ADD CONSTRAINT BOARDING_FLIGHT_FK FOREIGN KEY (FLIGHT_ID) REFERENCES SCHEDULE(FLIGHT_ID);
ALTER TABLE BOARDING ADD CONSTRAINT BOARDING_BOOKING_FK FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);

ALTER TABLE PASSENGER  
MODIFY (PHONE_NUMBER NOT NULL);

ALTER TABLE PASSENGER  
MODIFY (PASSPORT_NUMBER NOT NULL);

ALTER TABLE PASSENGER  
MODIFY (EMAIL_ID VARCHAR2(55 BYTE) NOT NULL);

ALTER TABLE PASSENGER  
MODIFY (ADDRESS VARCHAR2(55 BYTE) NOT NULL);

ALTER TABLE PASSENGER  
MODIFY (PHONE_NUMBER VARCHAR2(20) );

ALTER TABLE PASSENGER  
MODIFY (DATE_OF_BIRTH NVARCHAR2(20) );

ALTER TABLE AIRPORT  
MODIFY (NAME VARCHAR2(80 BYTE) );


ALTER TABLE AIRPORT 
ADD (AIRPORT_CODE VARCHAR2(20) NULL);

ALTER TABLE AIRPORT 
ADD (LATITUDE DOUBLE PRECISION NOT NULL);

ALTER TABLE AIRPORT 
ADD (LONGITUDE DOUBLE PRECISION NOT NULL);

ALTER TABLE AIRPORT 
ADD (ALTITUDE INTEGER NOT NULL);

ALTER TABLE AIRPORT 
ADD (TIMEZONE INTEGER NOT NULL);

ALTER TABLE AIRPORT  
MODIFY (CITY VARCHAR2(50 BYTE) );

ALTER TABLE AIRPORT  
MODIFY (COUNTRY VARCHAR2(50 BYTE) );
