-- CREATE TABLE BOARDING 
-- (
--   BOARDING_ID NUMBER NOT NULL 
-- , PASSENGER_ID NUMBER NOT NULL 
-- , FLIGHT_ID NUMBER NOT NULL 
-- , BOOKING_ID NUMBER NOT NULL 
-- , BAGGAGE_NUMBER NUMBER NOT NULL 
-- , BAGGAGE_WEIGHT FLOAT NOT NULL 
-- , SEAT_NUMBER VARCHAR2(20) NOT NULL 
-- , CONSTRAINT BOARDING_PK PRIMARY KEY 
--   (
--     BOARDING_ID 
--   )
--   ENABLE 
-- );

CREATE TABLE BOARDING(
   BOARDING_ID    INTEGER  NOT NULL PRIMARY KEY 
  ,BOOKING_ID     INTEGER  NOT NULL
  ,BAGGAGE_NUMBER INTEGER  NOT NULL
  ,BAGGAGE_WEIGHT INTEGER  NOT NULL
  ,SEAT_NUMBER    VARCHAR(3) NOT NULL
);
