CREATE TABLE BOOKING 
(
  BOOKING_ID NUMBER NOT NULL 
, FLIGHT_ID NUMBER NOT NULL 
, PASSENGER_ID NUMBER NOT NULL 
, CLASS VARCHAR2(20) NOT NULL 
, DATE_TIME TIMESTAMP NOT NULL 
, PAYMENT_STATUS VARCHAR2(20) NOT NULL 
, AMOUNT_PAYABLE FLOAT NOT NULL 
, CONSTRAINT BOOKING_PK PRIMARY KEY 
  (
    BOOKING_ID 
  )
  ENABLE 
);
