CREATE TABLE CREW_EXPENSE 
(
  EXPENSE_ID NUMBER NOT NULL 
, CREW_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, COST FLOAT NOT NULL 
, CONSTRAINT CREW_EXPENSE_PK PRIMARY KEY 
  (
    EXPENSE_ID 
  )
  ENABLE 
);
