DELETE FROM AIRPORT;

DELETE FROM ROUTE WHERE ROUTE_ID = 59;
DELETE FROM ROUTE WHERE ROUTE_ID = 60;
DELETE FROM ROUTE WHERE ROUTE_ID = 61;
DELETE FROM ROUTE WHERE ROUTE_ID = 62;
DELETE FROM ROUTE WHERE ROUTE_ID = 63;
DELETE FROM ROUTE WHERE ROUTE_ID = 64;
DELETE FROM ROUTE WHERE ROUTE_ID = 66;
DELETE FROM ROUTE WHERE ROUTE_ID = 67;
DELETE FROM ROUTE WHERE ROUTE_ID = 68;
DELETE FROM ROUTE WHERE ROUTE_ID = 69;
DELETE FROM ROUTE WHERE ROUTE_ID = 70;
DELETE FROM ROUTE WHERE ROUTE_ID = 71;
DELETE FROM ROUTE WHERE ROUTE_ID = 72;

DELETE FROM ROUTE WHERE ROUTE_ID = 52;
DELETE FROM ROUTE WHERE ROUTE_ID = 53;
DELETE FROM ROUTE WHERE ROUTE_ID = 54;
DELETE FROM ROUTE WHERE ROUTE_ID = 55;
DELETE FROM ROUTE WHERE ROUTE_ID = 4;
DELETE FROM ROUTE WHERE ROUTE_ID = 6;
DELETE FROM ROUTE WHERE ROUTE_ID = 7;
DELETE FROM ROUTE WHERE ROUTE_ID = 12;
DELETE FROM ROUTE WHERE ROUTE_ID = 13;
DELETE FROM ROUTE WHERE ROUTE_ID = 14;
DELETE FROM ROUTE WHERE ROUTE_ID = 15;
DELETE FROM ROUTE WHERE ROUTE_ID = 16;
DELETE FROM ROUTE WHERE ROUTE_ID = 17;
DELETE FROM ROUTE WHERE ROUTE_ID = 25;
DELETE FROM ROUTE WHERE ROUTE_ID = 33;
DELETE FROM ROUTE WHERE ROUTE_ID = 50;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;
DELETE FROM ROUTE WHERE ROUTE_ID = ;


