CREATE TABLE DISCOUNT_RATES 
(
  DISCOUNT_ID VARCHAR2(20) NOT NULL 
, PLATINUM VARCHAR2(20) NOT NULL 
, GOLD VARCHAR2(20) NOT NULL 
, SILVER VARCHAR2(20) NOT NULL 
, BRONZE VARCHAR2(20) NOT NULL 
, OFFER_START VARCHAR2(20) NOT NULL 
, OFFER_END VARCHAR2(20) 
, DESCRIPTION VARCHAR2(20) NOT NULL 
, CONSTRAINT DISCOUNT_RATES_PK PRIMARY KEY 
  (
    DISCOUNT_ID 
  )
  ENABLE 
);
