CREATE TABLE EMPLOYEE 
(
  EMPLOYEE_ID NUMBER(20) NOT NULL 
, FIRST_NAME VARCHAR2(50) NOT NULL 
, LAST_NAME VARCHAR2(50) NOT NULL 
, GENDER VARCHAR2(20) NOT NULL 
, PHONE_NUMBER VARCHAR2(20) NOT NULL 
, ADDRESS VARCHAR2(500) NOT NULL 
, EMAIL_ID VARCHAR2(50) 
, HIRE_DATE DATE NOT NULL 
, NATIONALITY VARCHAR2(40) NOT NULL 
, SALARY NUMBER NOT NULL 
, DESIGNATION VARCHAR2(100) NOT NULL 
, CONSTRAINT EMPLOYEE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
);
