CREATE TABLE SCHEDULE 
(
  FLIGHT_ID NUMBER NOT NULL 
, AIRCRAFT_ID NUMBER NOT NULL 
, ROUTE_ID NUMBER NOT NULL 
, ARRIVAL_DATE_TIME TIMESTAMP NOT NULL 
, DEPART_DATE_TIME TIMESTAMP NOT NULL 
, FLIGHT_TYPE VARCHAR2(20) NOT NULL 
, CONSTRAINT SCHEDULE_PK PRIMARY KEY 
  (
    FLIGHT_ID 
  )
  ENABLE 
);
