CREATE TABLE MAINTENANCE 
(
  COMPLAIN_ID NUMBER NOT NULL 
, PLANE_ID NUMBER NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, DEPARTMENT VARCHAR2(20) NOT NULL 
, OUT_OF_SERVICE DATE NOT NULL 
, BACK_TO_SERVICE DATE NOT NULL 
, CONSTRAINT MAINTENANCE_PK PRIMARY KEY 
  (
    COMPLAIN_ID 
  )
  ENABLE 
);
