CREATE TABLE PARTS_INFO 
(
  PARTS_ID NUMBER NOT NULL 
, PRICE FLOAT NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, DESCRIPTION VARCHAR2(20) 
, CONSTRAINT PARTS_INFO_PK PRIMARY KEY 
  (
    PARTS_ID 
  )
  ENABLE 
);
