--------------------------------------------------------
--  File created - Tuesday-January-02-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "BUETAIRLINES"."PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"CREDITCARD_NUMBER" NUMBER, 
	"CARDHOLDER_NAME" VARCHAR2(20 BYTE), 
	"CCV" NUMBER, 
	"EXPIRATION_DATE" VARCHAR2(20 BYTE), 
	"TOTAL_PAYABLE" NUMBER, 
	"DATE_OF_PAYMENT" DATE, 
	"PASSENGER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUETAIRLINES"."PAYMENT_PK" ON "BUETAIRLINES"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "BUETAIRLINES"."PAYMENT" ADD CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BUETAIRLINES"."PAYMENT" MODIFY ("TOTAL_PAYABLE" NOT NULL ENABLE);
  ALTER TABLE "BUETAIRLINES"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
