SELECT ARRIVAL_DATE_TIME , DEPARTURE_DATE_TIME
FROM FLIGHT F JOIN ROUTE D
ON (F.ROUTE_ID = D.ROUTE_ID)
JOIN AIRPORT E 
ON (E.AIRPORT_ID = D.SOURCE)
JOIN AIRPORT A
ON (A.AIRPORT_ID = D.DESTINATION)
WHERE ROUTE_ID = ANY 
(SELECT  D.ROUTE_ID 
FROM AIRPORT E JOIN ROUTE D
ON (E.AIRPORT_ID = D.SOURCE)
JOIN AIRPORT A
ON (A.AIRPORT_ID = D.DESTINATION)
WHERE D.SOURCE = ANY (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Dhaka'));

--WHERE D.SOURCE = ANY (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Dhaka')

--SELECT E.NAME,A.NAME, D.SOURCE , D.ROUTE_ID , D.DESTINATION
--      FROM AIRPORT E JOIN ROUTE D
--      ON (E.AIRPORT_ID = D.SOURCE)
--      JOIN AIRPORT A
--      ON (A.AIRPORT_ID = D.DESTINATION)
--      WHERE D.SOURCE = ANY (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Dhaka')


--SELECT 'RX'||ROUTE_ID , A.NAME || ' ' || A.CITY || ' , ' || A.COUNTRY "Source", D.NAME||' ' || D.CITY|| ' , ' || D.COUNTRY "Destination", F.ARRIVAL_DATE_TIME , 
--    F.DEPARTURE_DATE_TIME FROM FLIGHT F, AIRPORT A , AIRPORT D
--      WHERE ROUTE_ID = ANY 
--      (SELECT ROUTE_ID  FROM ROUTE  WHERE DESTINATION = ANY 
--      (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Dhaka')) AND A.CITY = 'Dhaka'
--        AND ROWNUM <= 100;
        

SELECT ROUTE_ID , A.NAME || ' ' || A.CITY || ' , ' || A.COUNTRY "Source", D.NAME||' ' || D.CITY|| ' , ' || D.COUNTRY "Destination", F.ARRIVAL_DATE_TIME , 
    F.DEPARTURE_DATE_TIME FROM FLIGHT F, AIRPORT A , AIRPORT D
      WHERE ROUTE_ID = ANY 
      (SELECT ROUTE_ID  FROM ROUTE  WHERE DESTINATION = ANY 
      (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Japan')) OR D.CITY = 'Japan'
        AND ROWNUM <= 100;
        
        
        
DESC AIRPORT;
DESC ROUTE;
DESC FLIGHT;

--SELECT F.ROUTE_ID , R.SOURCE , R.DESTINATION , F.ARRIVAL_DATE_TIME , F.DEPARTURE_DATE_TIME
--FROM ROUTE R FULL JOIN FLIGHT F
--ON (R.ROUTE_ID = F.ROUTE_ID)
--WHERE ((F.ARRIVAL_DATE_TIME IS NOT NULL) AND (F.DEPARTURE_DATE_TIME IS NOT NULL));

SELECT F.ROUTE_ID , R.SOURCE , A.NAME , R.DESTINATION , D.NAME , F.ARRIVAL_DATE_TIME , F.DEPARTURE_DATE_TIME
FROM ROUTE R FULL JOIN FLIGHT F
ON (R.ROUTE_ID = F.ROUTE_ID)
FULL JOIN AIRPORT A
ON(A.AIRPORT_ID = R.SOURCE)
FULL JOIN AIRPORT D
ON (D.AIRPORT_ID = R.DESTINATION)
WHERE ( F.FLIGHT_ID IS NOT NULL AND  F.ARRIVAL_DATE_TIME LIKE '2002%');

      
