SELECT * FROM AIRCRAFT;
SELECT * FROM AIRCRAFT_INFO;
SELECT * FROM AIRPORT;
SELECT * FROM BOARDING;
SELECT * FROM BOOKING;
SELECT * FROM CREW_EXPENSE;
SELECT * FROM DISCOUNT_RATES;
SELECT * FROM EMPLOYEE;
SELECT * FROM ENGINEER;
SELECT * FROM FLIGHT;
SELECT * FROM FLIGHT_CREW;
SELECT * FROM FUEL;
SELECT * FROM MAINTENANCE;
SELECT * FROM PARTS;
SELECT * FROM PARTS_INFO;
SELECT * FROM PASSENGER;
SELECT * FROM PRICE;
SELECT * FROM ROUTE;




