ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MON/YYYY HH24:MI:SS';

SELECT * FROM FLIGHT;

SELECT * FROM PASSENGER;
SELECT COUNT(*) FROM AIRCRAFT_INFO;
SELECT COUNT(*) FROM AIRCRAFT;
SELECT * FROM ROUTE;
SELECT COUNT(*) FROM AIRPORT;
SELECT * FROM AIRPORT WHERE name LIKE '%sINTERNATIONAL%s' ORDER BY COUNTRY DESC;

DELETE FROM FLIGHT;

SELECT F.AIRCRAFT_ID , (SELECT CITY FROM AIRPORT WHERE AIRPORT_ID =  R.SOURCE) "SOURCE" , R.DESTINATION ,F.ARRIVAL_DATE_TIME, F.DEPARTURE_DATE_TIME , F.STATUS , F.TYPE FROM FLIGHT F JOIN ROUTE R 
ON F.ROUTE_ID = R.ROUTE_ID;

COMMIT CHANGES;

SELECT F.AIRCRAFT_ID , A.CITY "SOURCE" , D.CITY "DESTINATION" ,F.ARRIVAL_DATE_TIME, F.DEPARTURE_DATE_TIME , F.STATUS , F.TYPE FROM FLIGHT F JOIN ROUTE R 
ON F.ROUTE_ID = R.ROUTE_ID
JOIN AIRPORT A
ON A.AIRPORT_ID = R.SOURCE
JOIN AIRPORT D ON D.AIRPORT_ID = R.DESTINATION;

SELECT * FROM ROUTE WHERE SOURCE = (SELECT AIRPORT_ID FROM AIRPORT WHERE CITY = 'Chittagong');


SELECT 'RX'||F.ROUTE_ID , A.AIRPORT_CODE  "Source", A.COUNTRY,
D.AIRPORT_CODE "Destination", D.COUNTRY, F.ARRIVAL_DATE_TIME  , 
(24 * extract(day from (F.ARRIVAL_DATE_TIME-F.DEPARTURE_DATE_TIME) day(9) to second))
          + extract(hour from (F.ARRIVAL_DATE_TIME-F.DEPARTURE_DATE_TIME) day(9) to second)
          + ((1/100) * extract(minute from (F.ARRIVAL_DATE_TIME-F.DEPARTURE_DATE_TIME) day(9) to second)) "DURATION",
F.DEPARTURE_DATE_TIME 
FROM ROUTE R FULL JOIN FLIGHT F
ON (R.ROUTE_ID = F.ROUTE_ID)
FULL JOIN AIRPORT A
ON(A.AIRPORT_ID = R.SOURCE)
FULL JOIN AIRPORT D
ON (D.AIRPORT_ID = R.DESTINATION)
WHERE ( F.FLIGHT_ID IS NOT NULL AND  A.COUNTRY = 'Bangladesh'
AND ROWNUM <= 20 );




--QUERY FOR TABLE SHOW
--fORMAT: SOURCE_CODE - DEST_CODE - TIME, ARR, DEPARTURE, - DURATION (IN ROUTE TABLE)

--INPUTS
--SOURCE CITY, AND DEST CITY
SELECT R.ROUTE_ID , S.CITY , S.AIRPORT_CODE , D.CITY , D.AIRPORT_CODE , F.ARRIVAL_DATE_TIME, R.DURATION, F.DEPARTURE_DATE_TIME 
FROM FLIGHT F JOIN ROUTE R
ON F.ROUTE_ID = R.ROUTE_ID
JOIN AIRPORT S
ON (S.AIRPORT_ID = R.SOURCE AND S.CITY = 'Chittagong')
JOIN AIRPORT D
ON (D.AIRPORT_ID = R.DESTINATION AND D.CITY = 'Dhaka');

SELECT PRICE
FROM PRICE_ITEM
WHERE PRICE_ID = ANY (SELECT PRICE_ID
FROM PRICE P
WHERE P.ROUTE_ID = 1030);

--PRICE ALL ROUTES
SELECT R.ROUTE_ID , C.NAME, I.PRICE
FROM ROUTE R JOIN PRICE P
ON R.ROUTE_ID = P.ROUTE_ID
RIGHT OUTER JOIN PRICE_ITEM I
ON P.PRICE_ID = I.PRICE_ID
JOIN PRICE_CATEGORY C
ON C.PRICE_CATEGORY_ID = I.PRICE_CATEGORY_ID;

--SPECIFIC ROUTE
SELECT R.ROUTE_ID , C.PRICE_CATEGORY_ID, I.PRICE
FROM ROUTE R JOIN PRICE P
ON R.ROUTE_ID = P.ROUTE_ID AND R.ROUTE_ID = 1030
JOIN PRICE_ITEM I
ON P.PRICE_ID = I.PRICE_ID
JOIN PRICE_CATEGORY C
ON C.PRICE_CATEGORY_ID = I.PRICE_CATEGORY_ID;


SELECT * FROM ADMIN;
